### ISSUE TITLE
save figures from st.pl.non_spatial_plot

### ISSUE THREAD

**Issue by zhengdongfeng** [BiomedicalMachineLearning/stLearn#128]
Thanks for your helpful tool stlearn. In your docs, I learn we can save figures generated from stlearn.pl.gene_plot using fname option, but I cannot find how to save figures generated from st.pl.non_spatial_plot, can you give me some advice? My stlearn version is 0.3.1.
I would appreciated for your help very much!

**Comment by duypham2108** [comment]
Hi, we wrap multiple plot functions from scanpy in this `st.pl.non_spatial_plot`. You can use these 3 functions in scanpy to save the plot:
```
import scanpy as sc
sc.pl.paga(adata, color=use_label, save="figure.png")
sc.pl.draw_graph(adata, color=use_label, legend_loc="on data", save="figure2.png")
sc.pl.draw_graph(adata, color="dpt_pseudotime", save="figure3.png")
```

**Comment by zhengdongfeng** [comment]
Thank you so much that you have solved my problem.

**Comment by zhengdongfeng** [comment]
I'm sorry to brother you again. I also cannot find how to save the figure generated from `st.pl.trajectory.local_plot`, I tried to use `plt.savefig`, but the figure output is empty. Can you give me some useful advices? I would appreciate you very much!
![Uploading 微信截图_20210908133234.png…]()

**Comment by zhengdongfeng** [comment]
I'm sorry to bother you again. I also cannot find how to save the figure generated from `st.pl.trajectory.local_plot`, I tried to use `plt
![微信截图_20210908133234](https://user-images.githubusercontent.com/58932073/132452096-b1c3a0a0-42a3-4ecc-832a-586c5a14bd2a.png)
.savefig`, but the figure output is empty. Can you give me some useful advices? I would appreciate you very much!

**Comment by zhengdongfeng** [comment]
I'm sorry to bother you again. I also cannot find how to save the figure generated from `st.pl.trajectory.local_plot`, I tried to use `plt.savefig`, but the figure output is empty. Can you give me some useful advices? I would appreciate you very much!
![微信截图_20210908133234](https://user-images.githubusercontent.com/58932073/132452162-a130a38d-3986-4af3-a6ac-1565244c0a44.png)

**Comment by duypham2108** [comment]
I fixed it in the github version, then you can save this type of plot after install the github version

**Comment by zhengdongfeng** [comment]
Thanks for your reply, I tried to clone this repository, and use `python setup.py install ` to install this github version, but encountered some error, for example, cannot find 'stlearn.tools.microenv', shown as below:
![QQ图片20210909100444](https://user-images.githubusercontent.com/58932073/132610418-9cf6640b-fab7-4c91-b492-f45332bca036.png)
can you give me some advices for solving this problem? Thank you very much.

**Comment by duypham2108** [comment]
Maybe you need to uninstall the old version first. Please try:
```
pip uninstall stlearn
python setup.py install
```

**Comment by zhengdongfeng** [comment]
Thank you. But I installed the old stlearn under independent virtual environment using conda in the server. Then I also tried to install this github version on my individual computer, which didn't install stlearn before, still failed, shown as below:
![1](https://user-images.githubusercontent.com/58932073/132629933-96bf2eb8-7f3b-4588-81e0-8a558966b8fc.png)
can you give me some advices for solving this problem? Thank you very much.

**Comment by duypham2108** [comment]
It's the issue of setuptools. Can you run this command:
```
pip install -U setuptools
```

**Comment by zhengdongfeng** [comment]
Thanks for your advice
